version: "3"

services:
  db:
    image: postgres:15.2-alpine
    hostname: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - pgadmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./.env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 7777:80
    restart: always
    networks:
      - pgadmin
    depends_on:
      - db
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    volumes:
      - ../.data/redis:/var/lib/redis/data
    env_file:
      - ./.env

volumes:
  pgdata:
  pgadmin:
  
networks:
  pgadmin:
    external: true
