version: "3"

services:
  db:
    image: postgres:15.2-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - pgadmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./.env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 7777:80
    restart: always
    networks:
      - pgadmin
    depends_on:
      - db

volumes:
  pgdata:
  pgadmin:
  
networks:
  pgadmin:
    external: true
